#!/usr/bin/env python3
"""Write the teaching content for the Learn syllabus.

WHY
    src/data/syllabus.ts defines 56 modules by hand: titles, ordering,
    prerequisites, and the links out to the LeetCode catalogue and the book
    shelf. That structure is the part worth controlling. This fills in the bulk
    prose for each one -- the explanation, glossary, quiz and code exercises --
    and writes it to src/data/modules.generated.ts, which is merged on top.

    Output is committed, so it ships with no runtime AI cost.

USAGE
    export $(grep -v '^#' .env.local | grep -v '^$' | xargs)
    python3 scripts/generate_modules.py --inspect --limit 2   # read first
    python3 scripts/generate_modules.py                       # full run

    Resumable: the checkpoint is written after every module.

A NOTE ON TRUST
    Generated lessons are a draft. The exercises carry executable tests, so a
    broken exercise fails visibly in the browser rather than teaching something
    wrong quietly -- but the prose needs a human read.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib import llm  # noqa: E402
from lib.detex import detex  # noqa: E402

SYLLABUS = Path("src/data/syllabus.ts")
OUT_PATH = Path("src/data/modules.generated.ts")
CHECKPOINT = Path("scripts/.modules_checkpoint.json")

SYSTEM = """You write the teaching material for a self-study curriculum aimed at quantitative trading and quantitative research internships. Your reader is a strong undergraduate who wants to be interview-ready, not an expert being reminded.

Write the module you are given. Produce, as one JSON object:

"elaboration": the explanation. 400-700 words of plain prose. Blank line between paragraphs; a line starting with "- " becomes a bullet. Build the idea up, state the key result, then say where it breaks or is misapplied in practice. Formulas inline in plain text, e.g. "C - P = S - K*e^(-rT)". NEVER use LaTeX or markdown syntax.

"keyNotes": 4-6 one-line takeaways worth memorising.

"glossary": 4-8 {"term", "definition"} pairs for the vocabulary this module introduces. One or two sentences each.

"quiz": 5-7 questions mixing three kinds.
  - {"kind":"mcq","prompt","choices":[4 strings],"answerIndex":0-3,"explanation","concept"}
  - {"kind":"numeric","prompt","answer":"<number as a string>","tolerance":<number>,"explanation","concept"}
  - {"kind":"free","prompt","answer":"<the model answer>","explanation","concept"}
  "concept" must be one of the glossary terms. Every distractor in an mcq must be plausible. Every numeric answer must be one you are certain of -- if you are not, ask a different question.

"exercises": 1-2 Python exercises, or an empty list when the module is not computational.
  {"title","prompt","starterCode","solution","tests","hint"}
  - starterCode defines the function signature with a TODO body.
  - solution is a complete working implementation.
  - tests is Python assert statements that pass against solution and fail against starterCode. They run in the browser after the user's code, so they must reference only what the user defines.
  - Only numpy and pandas are available. No file, network or plotting.
  - Keep runtimes under a second.

"videos": up to 2 {"title","url"} for lectures you are confident exist. Prefer an empty list to a guessed URL.

"sources": up to 3 {"label","url"?,"note"?}. Same rule: no invented links.

Accuracy matters more than completeness. A wrong formula in a lesson is worse than a thin lesson. Respond with a single JSON object and nothing else."""

USER = """MODULE: {title}
SUBJECT: {subject}
SUMMARY: {summary}
DIFFICULTY: {difficulty}
TARGET LENGTH: about {minutes} minutes of study
TAGS: {tags}
{prereqs}{leetcode}{books}"""


def load_outlines() -> list[dict]:
    """Reads the module outlines straight out of the TypeScript syllabus."""
    text = SYLLABUS.read_text()
    block = text[text.index("export const MODULE_OUTLINES"):]
    out = []
    for line in block.splitlines():
        line = line.strip()
        if not line.startswith("{ id:") or not line.endswith("},"):
            continue
        obj = line[:-1]
        obj = re.sub(r'(\{|,)\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*:', r'\1"\2":', obj)
        try:
            out.append(json.loads(obj))
        except json.JSONDecodeError as e:
            print(f"  ! could not parse outline: {e}")
    return out


def ts(v) -> str:
    return json.dumps(v, ensure_ascii=False)


def emit(modules: list[dict]) -> str:
    head = [
        "/* eslint-disable */",
        "// AUTO-GENERATED by scripts/generate_modules.py -- do not edit by hand.",
        "//",
        "// Teaching content for the modules whose structure lives in syllabus.ts.",
        "// Generated, so treat the prose as a draft; the exercises carry executable",
        "// tests, so a broken one fails visibly rather than misleading quietly.",
        "",
        "import type { Module } from '../models';",
        "",
        "export type GeneratedModule = Pick<",
        "  Module,",
        "  'id' | 'elaboration' | 'keyNotes' | 'glossary' | 'quiz' | 'exercises' | 'videos' | 'sources'",
        ">;",
        "",
        "export const MODULE_CONTENT: GeneratedModule[] = [",
    ]
    body = []
    for m in modules:
        body.append("  {")
        body.append(f"    id: {ts(m['id'])},")
        body.append(f"    elaboration: {ts(m['elaboration'])},")
        body.append(f"    keyNotes: {ts(m['keyNotes'])},")
        body.append(f"    glossary: {ts(m['glossary'])},")
        body.append(f"    quiz: {ts(m['quiz'])},")
        body.append(f"    exercises: {ts(m['exercises'])},")
        body.append(f"    videos: {ts(m.get('videos', []))},")
        body.append(f"    sources: {ts(m.get('sources', []))},")
        body.append("  },")
    return "\n".join(head + body + ["];", ""])


def as_code(value) -> str:
    """Code fields come back as a string or as a list of lines, depending on
    the model. Normalise to a string, or the tests are never really checked."""
    if isinstance(value, list):
        return "\n".join(str(line) for line in value)
    return str(value or "")


def _run(code: str, timeout: int = 20) -> tuple[bool, str]:
    """Runs a snippet in a separate interpreter. Returns (passed, message)."""
    try:
        proc = subprocess.run([sys.executable, "-c", code], capture_output=True,
                              text=True, timeout=timeout)
    except subprocess.TimeoutExpired:
        return False, "timed out"
    return proc.returncode == 0, (proc.stderr or proc.stdout).strip()[-300:]


def verify_exercise(ex: dict) -> str | None:
    """Checks an exercise actually works. Returns a reason to reject, or None.

    Two conditions, and the second matters as much as the first: the solution
    must pass the tests, AND the starter code must fail them. A test suite that
    passes against an unimplemented stub checks nothing, and would show a green
    tick before the user has written a line.
    """
    ok, err = _run(ex["solution"] + "\n" + ex["tests"])
    if not ok:
        return f"solution fails its own tests: {err}"
    ok, _ = _run(ex["starterCode"] + "\n" + ex["tests"])
    if ok:
        return "tests pass against the starter code, so they check nothing"
    return None


def clean_module(mid: str, raw: dict) -> dict | None:
    """Validates and normalises one generated module. None means unusable."""
    elaboration = detex((raw.get("elaboration") or "").strip())
    if len(elaboration) < 300:
        return None

    glossary = [
        {"term": (g.get("term") or "").strip(), "definition": detex((g.get("definition") or "").strip())}
        for g in raw.get("glossary") or []
        if (g.get("term") or "").strip() and (g.get("definition") or "").strip()
    ]
    terms = {g["term"].lower() for g in glossary}

    quiz = []
    for k, q in enumerate(raw.get("quiz") or []):
        kind = q.get("kind")
        prompt = detex((q.get("prompt") or "").strip())
        explanation = detex((q.get("explanation") or "").strip())
        if kind not in {"mcq", "numeric", "free"} or len(prompt) < 10:
            continue
        # Drop a concept tag that does not match the glossary, rather than
        # queueing review for a term that does not exist.
        concept = (q.get("concept") or "").strip()
        if concept and concept.lower() not in terms:
            concept = ""
        item = {"id": f"{mid}-q{k + 1}", "kind": kind, "prompt": prompt, "explanation": explanation}
        if concept:
            item["concept"] = concept

        if kind == "mcq":
            choices = [detex(str(c).strip()) for c in q.get("choices") or []]
            idx = q.get("answerIndex")
            if len(choices) < 3 or not isinstance(idx, int) or not 0 <= idx < len(choices):
                continue
            item["choices"] = choices
            item["answerIndex"] = idx
        elif kind == "numeric":
            try:
                float(str(q.get("answer")).strip())
            except (TypeError, ValueError):
                continue
            item["answer"] = str(q.get("answer")).strip()
            if isinstance(q.get("tolerance"), (int, float)):
                item["tolerance"] = q["tolerance"]
        else:
            answer = detex((q.get("answer") or "").strip())
            if len(answer) < 20:
                continue
            item["answer"] = answer
        quiz.append(item)

    exercises = []
    for k, e in enumerate(raw.get("exercises") or []):
        starter = as_code(e.get("starterCode"))
        solution = as_code(e.get("solution"))
        tests = as_code(e.get("tests"))
        if not (starter and solution and tests):
            continue
        # An exercise whose tests do not assert anything checks nothing.
        if "assert" not in tests:
            continue
        candidate = {
            "starterCode": starter, "solution": solution, "tests": tests,
        }
        reason = verify_exercise(candidate)
        if reason:
            print(f"      - dropped exercise {k + 1}: {reason}")
            continue

        exercises.append({
            "id": f"{mid}-e{k + 1}",
            "title": (e.get("title") or f"Exercise {k + 1}").strip(),
            "prompt": detex((e.get("prompt") or "").strip()),
            "starterCode": starter,
            "solution": solution,
            "tests": tests,
            **({"hint": detex(e["hint"].strip())} if e.get("hint") else {}),
        })

    if len(quiz) < 3:
        return None

    return {
        "id": mid,
        "elaboration": elaboration,
        "keyNotes": [detex(str(n).strip()) for n in (raw.get("keyNotes") or []) if str(n).strip()],
        "glossary": glossary,
        "quiz": quiz,
        "exercises": exercises,
        "videos": [v for v in (raw.get("videos") or []) if v.get("url", "").startswith("http")],
        "sources": [s for s in (raw.get("sources") or []) if s.get("label")],
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--inspect", action="store_true")
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--only", default="", help="substring match on the module id or title")
    ap.add_argument("--model", default=None)
    ap.add_argument("--restart", action="store_true")
    args = ap.parse_args()

    if not llm.is_configured():
        print("LLM_API_KEY is not set. See .env.example.")
        return 1

    outlines = load_outlines()
    print(f"loaded {len(outlines)} module outlines")

    if args.restart and CHECKPOINT.exists():
        CHECKPOINT.unlink()
    done: dict[str, dict] = {}
    if CHECKPOINT.exists():
        done = json.loads(CHECKPOINT.read_text())
        print(f"resuming: {len(done)} already written")

    targets = [o for o in outlines
               if args.only.lower() in o["id"].lower() or args.only.lower() in o["title"].lower()]
    pending = [o for o in targets if o["id"] not in done]
    if args.limit:
        pending = pending[: args.limit]

    model = args.model or llm.model_for("smart")
    print(f"{len(pending)} module(s) to write with {model}\n")
    usage = llm.Usage()

    for n, o in enumerate(pending, 1):
        prereqs = f"\nBUILDS ON: {', '.join(o['prereqs'])}" if o.get("prereqs") else ""
        leetcode = f"\nLINKED LEETCODE PROBLEMS: {', '.join(o['leetcodeIds'])}" if o.get("leetcodeIds") else ""
        books = ""
        if o.get("bookRefs"):
            books = "\nREAD ALONGSIDE: " + ", ".join(
                f"{r['bookId']}" + (f" ch.{r['chapter']}" if r.get("chapter") else "") for r in o["bookRefs"])

        try:
            raw = llm.chat(
                system=SYSTEM,
                user=USER.format(title=o["title"], subject=o["subjectId"], summary=o["summary"],
                                 difficulty=o["difficulty"], minutes=o["estMinutes"],
                                 tags=", ".join(o.get("tags", [])),
                                 prereqs=prereqs, leetcode=leetcode, books=books),
                model=model, max_tokens=9000, usage=usage,
            )
        except llm.LlmError as e:
            print(f"[{n}/{len(pending)}] ! {o['id']}: {e}")
            continue
        except Exception as e:  # noqa: BLE001 - one bad module must not end the run
            print(f"[{n}/{len(pending)}] ! {o['id']}: unexpected {type(e).__name__}: {e}")
            continue

        cleaned = clean_module(o["id"], raw if isinstance(raw, dict) else {})
        if cleaned is None:
            print(f"[{n}/{len(pending)}] REJECT {o['id']} (too thin or malformed)")
            continue

        done[o["id"]] = cleaned
        print(f"[{n}/{len(pending)}] ok {o['id']}: "
              f"{len(cleaned['elaboration'])} chars, {len(cleaned['quiz'])} quiz, "
              f"{len(cleaned['exercises'])} exercise(s), {len(cleaned['glossary'])} terms")
        if args.inspect:
            print("      " + cleaned["elaboration"][:400].replace("\n", "\n      "))
            print()
        if not args.inspect:
            CHECKPOINT.write_text(json.dumps(done, ensure_ascii=False))

    print(f"\n{len(done)} module(s) written | tokens {usage.prompt} in / {usage.completion} out")
    if args.inspect:
        print("--inspect: nothing written.")
        return 0
    if not done:
        print("Nothing to write.")
        return 1

    ordered = [done[o["id"]] for o in outlines if o["id"] in done]
    OUT_PATH.write_text(emit(ordered))
    print(f"wrote {len(ordered)} module(s) to {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
