/* eslint-disable */
// AUTO-GENERATED by scripts/generate_modules.py -- do not edit by hand.
//
// Teaching content for the modules whose structure is defined in syllabus.ts.
// Committed empty so the merge layer can import it unconditionally; run the
// script to populate it.

import type { Module } from '../models';

export type GeneratedModule = Pick<
  Module,
  'id' | 'elaboration' | 'keyNotes' | 'glossary' | 'quiz' | 'exercises' | 'videos' | 'sources'
>;

export const MODULE_CONTENT: GeneratedModule[] = [];
