/* eslint-disable */
// AUTO-GENERATED by scripts/generate_quant_bank.py -- do not edit by hand.
//
// Placeholder until the generator is run. Committed empty so the deck loader
// can import it unconditionally.

import type { FlashcardSeed } from '../models';

export const QUANT_BANK_SEEDS: FlashcardSeed[] = [];
